### ISSUE TITLE
Adição de Colaboradores

### ISSUE THREAD

**Issue by carlosbazilio** [JoaoVitorSantiagoNogueira/Trabalho-progweb-joaoNogueira-matheusLobo-RamonFerreira#1]
Olá João Vitor,
Lembre de adicionar o Matheus Lobo e o Ramon como colaboradores desse projeto.
Abraços!

**Comment by carlosbazilio** [comment]
Pessoal, quem é o usuário @flamethrow ?

**Comment by flamethrow** [comment]
Fala Bazilio, foi mal, essa conta é uma outra minha que eu criei só pra
fazer uns testes de pull request / merge antes. No primeiro commit eu
comittei com essa conta sem querer, mas não consigo apagar esse commit do
repositório.

Em qui, 1 de out de 2020 17:28, Carlos Bazilio <notifications@github.com>
escreveu:

**Comment by flamethrow** [comment]
E sou eu, Ramon

Em qui, 1 de out de 2020 17:51, Ra Fer <r2flamethrow@gmail.com> escreveu:

**Comment by ramondsf92** [comment]
Fala Bazilio, foi mal, essa conta é uma outra minha que eu criei só pra
fazer uns testes de pull request / merge antes. No primeiro commit eu
comittei com essa conta sem querer, mas não consigo apagar esse commit do
repositório.
